#
# Blog Settings
#
author: Lucas Pains
url: http://lpains.net
title: Pains
subtitle: of a geek
description: A blog about all the pains (name pun intended) faced by a geek while trying to conquer the word building software.
email_md5: 0ce5a3e31c584a3c81fa6a458810f2be
subscribe_rss: http://lpains.net/atom.xml
url: http://lpains.net/

# social
github_user: jlucaspains
github_repo_url: https://github.com/jlucaspains/blog/

twitter_user: lucaspains
twitter_tweet_count: 5
twitter_show_replies: false
twitter_tweet_button: true

linkedin_user: lucaspains

google_analytics_tracking_id: UA-44645930-2

addthis_profile_id: ra-5c60c593dcb02fe9

kramdown:
  hard_wrap: false

#
# Jekyll Settings
#
permalink: /articles/:year/:title/
paginate: 2
paginate_path: "/:num/"
category_dir: categories

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag